version: '3'

services:
  web_nginx_2:
    image: nginx
    container_name: nginx_container_2
    networks:
      - my_network
    ports:
      - "8082:80"
  web_httpd:
    image: httpd
    container_name: httpd_container
    networks:
      - my_network
    ports:
      - 8081:80

networks:
  my_network:
    driver: bridge
